<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3N7FDE7" failures="1" tests="12" name="paracheck" time="13.585" errors="0" timestamp="2025-01-23T12:33:01 IST">
  <testcase classname="testcases.SignInTest" name="ValidateUrl" time="0.422"/>
  <testcase classname="testcases.SignInTest" name="IsLogoDisplayed" time="0.115"/>
  <testcase classname="testcases.SignInTest" name="IsWelcomeDisplayed" time="0.205"/>
  <testcase classname="testcases.SignInTest" name="IsrememberDisplayed" time="0.094"/>
  <testcase classname="testcases.SignInTest" name="SignInDisplayed" time="0.06"/>
  <testcase classname="testcases.SignInTest" name="rememberClick" time="0.222"/>
  <testcase classname="testcases.SignInTest" name="IsForgot" time="0.348">
    <failure type="java.lang.AssertionError" message="did not expect [https://erpindia.inscol.com/auth/sign-in] but found [https://erpindia.inscol.com/auth/sign-in]">
      <![CDATA[java.lang.AssertionError: did not expect [https://erpindia.inscol.com/auth/sign-in] but found [https://erpindia.inscol.com/auth/sign-in]
at testcases.SignInTest.IsForgot(SignInTest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- IsForgot -->
  <testcase classname="testcases.SignInTest" name="enterusername" time="0.481"/>
  <testcase classname="testcases.SignInTest" name="passwordToggleTest" time="0.677"/>
  <testcase classname="testcases.SignInTest" name="enterpassword" time="0.327"/>
  <testcase classname="testcases.SignInTest" name="register" time="0.412"/>
  <testcase classname="testcases.SignInTest" name="IsSignClicked" time="0.532"/>
</testsuite> <!-- paracheck -->
